config/routes.rb
Rails.application.routes.draw do
  resources :license_codes
  resources :license_histories, only: [:index, :show]
  resources :burn_histories, only: [:index, :show]
  resources :product_histories, only: [:index, :show] do
    member do
      get 'examine'
      get 'unexamine'
    end
  end
  resources :syslogs, only: [:index, :show]
  resources :hosts
  resources :products
  resources :solutions
  resources :protocols
  resources :categories
  resources :licenses
  post 'licenses/invalid'
  post 'licenses/import'
  post 'licenses/export'
  post 'licenses/generate'
  resources :tools do
    member do
      get 'download'
    end
  end
  resources :upgrades do
    member do
      get 'download'
    end
  end
  resources :schemes do
    member do
      get 'download'
    end
  end
  resources :firmwares do
    member do
      get 'download'
    end
  end
  resources :attaches
  get 'contact/index'
  get 'about/index'
  get 'home/index'

  namespace :api do
    namespace :v1 do
      get 'products/model'
      get 'licenses/snid'
      get 'licenses/auto'
      resources :sessions, only: [:create, :destroy]
      resources :users, only: [:index, :show]
      resources :attaches, only: [:show]
      resources :firmwares, only: [:index, :show]
      resources :schemes, only: [:index, :show]
      resources :upgrades, only: [:index, :show]
      resources :tools, only: [:index, :show]
      resources :products, only: [:index, :show]
      resources :licenses, only: [:index, :show]
      resources :license_codes, only: [:index, :show]
      resources :burn_histories, only: [:index, :show, :create]
      resources :license_histories, only: [:index, :show, :create]
    end
  end
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  post 'users/add_role'
  resources :roles
  root 'home#index'

end

app/models/license_code.rb
class LicenseCode < ActiveRecord::Base
  after_create :stored_create_log
  before_update :stored_update_log
  before_destroy :stored_delete_log

  def stored_create_log
    Syslog.stored_log("添加SN代号", "代号：#{self.code}，描述：#{self.description}")
  end

  def stored_update_log
    old = LicenseCode.find(self.id)
    ary = []
    ary << "名称：#{old.code} -> #{self.code}" if old.code != self.code
    ary << "描述：#{old.description} -> #{self.description}" if old.description != self.description
    
    if ary.size > 0
      title = "修改SN代号"
      content = "[#{old.code}] " + ary * ", "
      Syslog.stored_log(title, content)
    end
  end

  def stored_delete_log
    Syslog.stored_log("删除SN代号", "名称：#{self.name}")
  end
end

app/controllers/api/v1/license_codes_controller.rb
class Api::V1::LicenseCodesController < Api::V1::BaseController
  before_filter :authenticate_user_from_token!

  def index
    license_codes = LicenseCode.all
    render json: ActiveModel::ArraySerializer.new(license_codes, each_serializer: Api::V1::LicenseCodeSerializer, root: 'license_codes')
  end

  def show
    license_code = LicenseCode.find(params[:id])
    render json: Api::V1::LicenseCodeSerializer.new(license_code).to_json
  end
end

app/controllers/license_codes_controller.rb
class LicenseCodesController < ApplicationController
  authorize_resource
  before_action :set_license_code, only: [:show, :edit, :update, :destroy]

  # GET /license_codes
  # GET /license_codes.json
  def index
    @license_codes = LicenseCode.all.order(created_at: :desc).paginate(page:params[:page], per_page: 10)
  end

  # GET /license_codes/1
  # GET /license_codes/1.json
  def show
  end

  # GET /license_codes/new
  def new
    @license_code = LicenseCode.new
  end

  # GET /license_codes/1/edit
  def edit
  end

  # POST /license_codes
  # POST /license_codes.json
  def create
    @license_code = LicenseCode.new(license_code_params)

    respond_to do |format|
      if @license_code.save
        format.html { redirect_to @license_code, notice: 'License code was successfully created.' }
        format.json { render :show, status: :created, location: @license_code }
      else
        format.html { render :new }
        format.json { render json: @license_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /license_codes/1
  # PATCH/PUT /license_codes/1.json
  def update
    respond_to do |format|
      if @license_code.update(license_code_params)
        format.html { redirect_to @license_code, notice: 'License code was successfully updated.' }
        format.json { render :show, status: :ok, location: @license_code }
      else
        format.html { render :edit }
        format.json { render json: @license_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /license_codes/1
  # DELETE /license_codes/1.json
  def destroy
    @license_code.destroy
    respond_to do |format|
      format.html { redirect_to license_codes_url, notice: 'License code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_license_code
      @license_code = LicenseCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def license_code_params
      params.require(:license_code).permit(:code, :description, :status)
    end
end

app/helpers/api/v1/license_code_helper.rb
module Api::V1::LicenseCodeHelper
end

app/helpers/license_codes_helper.rb
module LicenseCodesHelper
end

app/views/license_codes/_form.html.erb
<%= form_for @license_code, :html => { :class => "form-horizontal license_code" } do |f| %>

  <% if @license_code.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@license_code.errors.count, "error") %> prohibited this license_code from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @license_code.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'form-control' %>
    </div>
    <%= error_span(@license_code[:code]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@license_code[:description]) %>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.hidden_field :status, :value => "1", :class => 'form-control' %>
    </div>
    <%= error_span(@license_code[:status]) %>
  </div>

  <br>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            license_codes_path, :class => 'btn btn-default' %>

<% end %>

app/views/license_codes/edit.html.erb
<%- model_class = LicenseCode -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/license_codes/index.html.erb
<%- model_class = LicenseCode -%>
<div class="page-header">
  <h2>
    <%=t '.title', :default => model_class.model_name.human %>
    <p class="pull-right">
      <% if can? :create, LicenseCode %>
      <%= link_to t('.new', :default => t("helpers.links.new")),
            new_license_code_path,
            :class => 'btn btn-primary' %>
      <% end %>
    </p>
  </h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @license_codes.each do |license_code| %>
      <tr>
        <td><%= link_to license_code.code, license_code_path(license_code) %></td>
        <td><%= license_code.description %></td>
        <td><%= license_code.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td>
          <% if can? :create, LicenseCode %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      license_code_path(license_code), :class => 'btn btn-default btn-xs' %>
          <% end %>

          <% if can? :update, LicenseCode %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_license_code_path(license_code), :class => 'btn btn-default btn-xs' %>
          <% end %>
          
          <% if can? :destroy, LicenseCode %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      license_code_path(license_code),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: "shared/pagination", object: @license_codes, as: :paginations %>

app/views/license_codes/new.html.erb
<%- model_class = LicenseCode -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/license_codes/show.html.erb
<%- model_class = LicenseCode -%>
<div class="page-header">
  <h2>
    <%=t '.title', :default => model_class.model_name.human.titleize %>:
    <%= @license_code.code %>
    <p class="pull-right">
      <%= link_to t('.back', :default => t("helpers.links.back")),
              license_codes_path, :class => 'btn btn-default'  %>

      <% if can? :update, LicenseCode %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_license_code_path(@license_code), :class => 'btn btn-default' %>
      <% end %>

      <% if can? :destroy, LicenseCode %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              license_code_path(@license_code),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
      <% end %>
    </p>
  </h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @license_code.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @license_code.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @license_code.status %></dd>
</dl>