config/routes.rb
Rails.application.routes.draw do
  resources :license_codes
  resources :license_histories, only: [:index, :show]
  resources :burn_histories, only: [:index, :show]
  resources :product_histories, only: [:index, :show] do
    member do
      get 'examine'
      get 'unexamine'
    end
  end
  resources :syslogs, only: [:index, :show]
  resources :hosts
  resources :products
  resources :solutions
  resources :protocols
  resources :categories
  resources :licenses
  post 'licenses/invalid'
  post 'licenses/import'
  post 'licenses/export'
  post 'licenses/generate'
  resources :tools do
    member do
      get 'download'
    end
  end
  resources :upgrades do
    member do
      get 'download'
    end
  end
  resources :schemes do
    member do
      get 'download'
    end
  end
  resources :firmwares do
    member do
      get 'download'
    end
  end
  resources :attaches
  get 'contact/index'
  get 'about/index'
  get 'home/index'

  namespace :api do
    namespace :v1 do
      get 'products/model'
      get 'licenses/snid'
      get 'licenses/auto'
      resources :sessions, only: [:create, :destroy]
      resources :users, only: [:index, :show]
      resources :attaches, only: [:show]
      resources :firmwares, only: [:index, :show]
      resources :schemes, only: [:index, :show]
      resources :upgrades, only: [:index, :show]
      resources :tools, only: [:index, :show]
      resources :products, only: [:index, :show]
      resources :licenses, only: [:index, :show]
      resources :license_codes, only: [:index, :show]
      resources :burn_histories, only: [:index, :show, :create]
      resources :license_histories, only: [:index, :show, :create]
    end
  end
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  post 'users/add_role'
  resources :roles
  root 'home#index'

end

app/models/burn_history.rb
class BurnHistory < ActiveRecord::Base
  belongs_to :operater, class_name: "User"
  belongs_to :product
  belongs_to :firmware
  belongs_to :scheme

  after_create :stored_create_log

  def stored_create_log
    ary = []
    ary << "产品：#{self.product.model}" if self.product
    ary << "固件：#{self.firmware.name}" if self.firmware
    ary << "配置：#{self.scheme.name}" if self.scheme
    ary << "操作人：#{self.operater.name}" if self.operater
    
    if ary.size > 0
      title = "烧写固件配置"
      content = "[#{self.product.model}] " + ary * ", "
      Syslog.stored_log(title, content, self.operater_id)
    end
  end
end

app/controllers/api/v1/burn_histories_controller.rb
class Api::V1::BurnHistoriesController < Api::V1::BaseController
  before_filter :authenticate_user_from_token!

  def index
    burn_histories = BurnHistory.all
    render json: ActiveModel::ArraySerializer.new(burn_histories, each_serializer: Api::V1::BurnHistorySerializer, root: 'burn_histories')
  end

  def show
    burn_history = BurnHistory.find(params[:id])
    render json: Api::V1::BurnHistorySerializer.new(burn_history).to_json
  end

  def create
    burn_history = BurnHistory.new(create_params)
    if burn_history.save
      render json: Api::V1::BurnHistorySerializer.new(burn_history).to_json, status: 201
    else
      return api_error status: 204
    end
  end


  private

  def create_params
    params.require(:burn_history).permit(:operater_id, :product_id, :firmware_id, :scheme_id)
  end
end

app/controllers/burn_histories_controller.rb
class BurnHistoriesController < ApplicationController
  authorize_resource
  before_action :set_burn_history, only: [:show, :edit, :update, :destroy]

  # GET /burn_histories
  # GET /burn_histories.json
  def index
    @burn_histories = BurnHistory.all.order(created_at: :desc).paginate(page:params[:page], per_page: 10)
  end

  # GET /burn_histories/1
  # GET /burn_histories/1.json
  def show
  end

  # GET /burn_histories/new
  def new
    @burn_history = BurnHistory.new
  end

  # GET /burn_histories/1/edit
  def edit
  end

  # POST /burn_histories
  # POST /burn_histories.json
  def create
    @burn_history = BurnHistory.new(burn_history_params)

    respond_to do |format|
      if @burn_history.save
        format.html { redirect_to @burn_history, notice: 'Burn history was successfully created.' }
        format.json { render :show, status: :created, location: @burn_history }
      else
        format.html { render :new }
        format.json { render json: @burn_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /burn_histories/1
  # PATCH/PUT /burn_histories/1.json
  def update
    respond_to do |format|
      if @burn_history.update(burn_history_params)
        format.html { redirect_to @burn_history, notice: 'Burn history was successfully updated.' }
        format.json { render :show, status: :ok, location: @burn_history }
      else
        format.html { render :edit }
        format.json { render json: @burn_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burn_histories/1
  # DELETE /burn_histories/1.json
  def destroy
    @burn_history.destroy
    respond_to do |format|
      format.html { redirect_to burn_histories_url, notice: 'Burn history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_burn_history
      @burn_history = BurnHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def burn_history_params
      params.require(:burn_history).permit(:description, :operater_id, :product_id, :firmware_id, :scheme_id)
    end
end

app/helpers/api/v1/burn_histories_helper.rb
module Api::V1::BurnHistoriesHelper
end

app/helpers/burn_histories_helper.rb
module BurnHistoriesHelper
end

app/views/burn_histories/_form.html.erb
<%= form_for @burn_history, :html => { :class => "form-horizontal burn_history" } do |f| %>

    <% if @burn_history.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@burn_history.errors.count, "error") %> prohibited this burn_history from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @burn_history.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@burn_history[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :operater_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :operater_id, :class => 'form-control' %>
    </div>
    <%= error_span(@burn_history[:operater_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :product_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :product_id, :class => 'form-control' %>
    </div>
    <%= error_span(@burn_history[:product_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :firmware_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :firmware_id, :class => 'form-control' %>
    </div>
    <%= error_span(@burn_history[:firmware_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :scheme_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :scheme_id, :class => 'form-control' %>
    </div>
    <%= error_span(@burn_history[:scheme_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            burn_histories_path, :class => 'btn btn-default' %>

<% end %>

app/views/burn_histories/edit.html.erb
<%- model_class = BurnHistory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/burn_histories/index.html.erb
<%- model_class = BurnHistory -%>
<div class="page-header">
  <h2>
    <%=t '.title', :default => model_class.model_name.human %>
  </h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:operater_id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:firmware_id) %></th>
      <th><%= model_class.human_attribute_name(:scheme_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @burn_histories.each do |burn_history| %>
      <tr>
        <td><%= link_to burn_history.operater.name, burn_history_path(burn_history) if burn_history.operater %></td>
        <td><%= burn_history.product.model if burn_history.product %></td>
        <td><%= burn_history.firmware.name if burn_history.firmware %></td>
        <td><%= burn_history.scheme.name if burn_history.scheme %></td>
        <td><%= burn_history.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: "shared/pagination", object: @burn_histories, as: :paginations %>

app/views/burn_histories/new.html.erb
<%- model_class = BurnHistory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/burn_histories/show.html.erb
<%- model_class = BurnHistory -%>
<div class="page-header">
  <h2>
    <%=t '.title', :default => model_class.model_name.human.titleize %>
    <p class="pull-right">
    <%= link_to t('.back', :default => t("helpers.links.back")),
              burn_histories_path, :class => 'btn btn-default'  %>
    </p>
  </h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:operater_id) %>:</strong></dt>
  <dd><%= @burn_history.operater.name if @burn_history.operater %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @burn_history.product.model if @burn_history.product %></dd>
  <dt><strong><%= model_class.human_attribute_name(:firmware_id) %>:</strong></dt>
  <dd><%= @burn_history.firmware.name if @burn_history.firmware %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scheme_id) %>:</strong></dt>
  <dd><%= @burn_history.scheme.name if @burn_history.scheme %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @burn_history.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @burn_history.created_at.strftime("%Y-%m-%d %H:%M:%S") %></dd>
</dl>